### ISSUE TITLE
Bugs signalés Teamworks Linux

### ISSUE THREAD

**Issue by cg90160** [Noethys/Teamworks#1]
Bonjour Ivan,

Je n'utilise pas Teamworks, mais j'ai été sollicité par Jakes pour aider des linuxiens en difficulté.
Voici 2 discussions à lire:
http://teamworks.forumactif.com/t275-teamworks-plante-au-demarrage-sous-xubuntu-16-04-2-64-bits
http://teamworks.forumactif.com/t285-teamworks-ne-se-lance-pas-ubuntu#957

Pour le 1er on avait rencontré le problème avec noethys, modification de la librairie PIL qui veut tobytes à la place de tostring.
Par rapport à mon message du forum, il y a d'autres scripts de l'appli qui sont concernés.

Pour le 2ème, il faudrait modifier le message install sous linux qu'on trouve dans le forum.

**Comment by Noethys** [comment]
Bonjour Claude,

Les modifications demandées ont été effectuées. Aurais-tu le temps de vérifier que la nouvelle procédure d'installation fonctionne bien sous Linux et est suffisamment explicite ? J'ai essayé de faire au plus simple.

Merci !

**Comment by cg90160** [comment]
Salut,

Ah tu as tout passé en python3 ?
Super boulot.
Pour répondre à ta question, brutalement je te dirai non ça ne fonctionne pas.
Je suis toujours sous debian, en version stable python est en version 3.5 et est déjà installé par défaut.
La 3.7 est-elle impérative ?
Mais surtout ce qui bloque:
- pip n'est pas installé par défaut donc toujours spécifique à debian, il faut faire un apt install python3-pip

- erreur à l'install de pypiwin32, je n'ai pas trouvé la solution, alors j'ai continué l'install sans :
Collecting pypiwin32
  Using cached https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting pywin32>=223 (from pypiwin32)
  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32)

- Pour wxpython, malheureusement ça dépend aussi des distributions. Il faudra peut-être différencier dans ton texte d'explication. Pour debian par exemple c'est:
pip3 install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-9/ wxPython
Tu trouveras les choix possibles à cette adresse: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/

- Et pour finir lorsque je lance l'appli, j'ai une première erreur à cause des accents dans le fichier versions:
File "Teamworks.py", line 60, in <module>
    VERSION_APPLICATION = FonctionsPerso.GetVersionTeamworks()
  File "/home/cgirard2/Teamworks-master/teamworks/FonctionsPerso.py", line 1093, in GetVersionTeamworks
    txtVersion = fichierVersion.readlines()[0]
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 100: invalid continuation byte

Et si je vire les lignes avec accent du fichier versions, j'arrive à démarrer, mais je tombe sur une autre erreur:
## 01/04/2019 11:44:18 | 2.1.0.2 | wxPython 4.0.4 gtk3 (phoenix) wxWidgets 3.0.5 | linux Linux 4.18.0-0.bpo.3-amd64 x86_64 ##
Traceback (most recent call last):
  File "Teamworks.py", line 1561, in OnInit
    frame.Annonce()
  File "Teamworks.py", line 1369, in Annonce
    versionAnnonce = self.ConvertVersionTuple(self.GetVersionAnnonce())
  File "Teamworks.py", line 781, in ConvertVersionTuple
    for num in texteVersion.split("."):
AttributeError: 'tuple' object has no attribute 'split'

Voilà pour mes premières investigations. J'aurais aimé pouvoir te dire que ça roule ...

**Comment by Noethys** [comment]
Salut,

Merci pour tes premiers retours, je vais regarder ça de près !

**Comment by cg90160** [comment]
Je vais regarder pour me mettre un environnement de test et j'essaierai de debugger.

**Comment by Noethys** [comment]
Je fais actuellement le développement sur un environnement virtuel sous python 3.7. Et je teste de temps en temps sur Python 2.7 pour conserver la rétrocompatibilité. 
Le dernier bug ("frame.Annonce") est corrigé. Par contre, c'est le bug sur l'unicode avec "fichierVersion.readlines()[0]" qui m'étonne car je ne peux pas le reproduire.

**Comment by cg90160** [comment]
Le fichier Versions.txt qui est sur ton dépôt n'est pas encodé en UTF8, je l'ai converti et cette fois c'est bon.
Le voici en UTF8.
[Versions.txt](https://github.com/Noethys/Teamworks/files/3098016/Versions.txt)

Ensuite je n'ai pas le fichier exemple à ouvrir, et lorsque je veux en créer un nouveau j'ai cette erreur:

Recuperation du num de version de la MAJ sur internet impossible.
La connexion avec la base de donnees SQLITE a echouee : 
Erreur detectee :argument 1 must be str, not bytes
--------- Attention, il reste 1 connexions encore ouvertes : ---------

**Comment by cg90160** [comment]
C'est ligne 131 de GestionDB.py
Le .encode('utf-8') ne passe pas, si je l'enlève c'est bon
Il faut que je regarde la syntaxe de sqlite3.connect que je ne connais pas.
Je vais essayer sur une base réseau qui ne doit pas être en sqlite si tu as fait comme pour Noethys

**Comment by cg90160** [comment]
Bien entendu idem pour les autres lignes où tu as la même syntaxe de sqlite3.connect.

Si je vais plus loin création d'une personne, j'ai ausi une erreur, voici mon journal:

-------- 19/04/2019 14:26:19 | 2.1.0.2 | Python 3 | wxPython 4.0.4 gtk3 (phoenix) wxWidgets 3.0.5 | linux Linux 4.18.0-0.bpo.3-amd64 x86_64  --------
<urlopen error timed out>
Recuperation du num de version de la MAJ sur internet impossible.
Traceback (most recent call last):
  File "/home/cgirard2/teamworks/Ctrl/CTRL_Personnes.py", line 431, in OnBoutonAjouter
    self.listCtrl_personnes.Ajouter()
  File "/home/cgirard2/teamworks/Ol/OL_personnes.py", line 560, in Ajouter
    dlg = DLG_Fiche_individuelle.Dialog(self.GetParent(), IDpersonne=0)
  File "/home/cgirard2/teamworks/Dlg/DLG_Fiche_individuelle.py", line 181, in __init__
    self.notebook = Notebook(self.panel_1, IDpersonne=self.IDpersonne)
  File "/home/cgirard2/teamworks/Dlg/DLG_Fiche_individuelle.py", line 83, in __init__
    self.pagePresences = CTRL_Page_presences.Panel(self, IDpersonne=self.IDpersonne)
  File "/home/cgirard2/teamworks/Ctrl/CTRL_Page_presences.py", line 33, in __init__
    self.listCtrl = ListCtrl(self, IDpersonne=self.IDpersonne)
  File "/home/cgirard2/teamworks/Ctrl/CTRL_Page_presences.py", line 467, in __init__
    self.SetSelection(index=self.indexEnCours, selection=False)
  File "/home/cgirard2/teamworks/Ctrl/CTRL_Page_presences.py", line 681, in SetSelection
    self.EnsureVisible(index)
wx._core.wxAssertionError: C++ assertion "index >= 0 && (size_t)index < GetItemCount()" failed at /home/vagrant/wxPython-4.0.4/ext/wxWidgets/src/generic/listctrl.cpp(4129) in EnsureVisible(): invalid index in EnsureVisible

--------- Attention, il reste 1 connexions encore ouvertes : ---------
>> IDconnexion = 632141 (0 requetes) :

**Comment by Noethys** [comment]
Salut,

Il me semble avoir réussi à corriger les bugs que tu évoques SAUF le ".encode('utf-8')". Parce que là, il y a un truc qui m'étonne : c'est le même code que Noethys. Noethys fonctionne normalement chez toi ?
