### ISSUE TITLE
Impression tableau impossible

### ISSUE THREAD

**Issue by Julien-asv** [Noethys/Teamworks#2]
Bonjour,

Désolé je ne trouve pas ou créer un compte sur votre forum...

J'ai une erreur pour imprimer le tableau. version windows.

`## 20/11/2020 10:56:04 | 2.1.1.9 | wxPython 4.0.4 msw (phoenix) wxWidgets 3.0.5 | win32 Windows 10 AMD64 ##
Traceback (most recent call last):
  File "C:\Users\Ivan\Documents\GitHub\Teamworks\teamworks\Dlg\DLG_Statistiques.py", line 1248, in OnBoutonImprimerTableau
  File "C:\Users\Ivan\Documents\GitHub\Teamworks\teamworks\Dlg\DLG_Statistiques.py", line 1271, in ConvertCouleur
ValueError: too many values to unpack (expected 3)
`

merci.

**Comment by Noethys** [comment]
Bonjour,

J'ai dû désactiver les inscriptions en raison d'attaques de spams ces derniers temps.

Je viens de corriger le bug. Une nouvelle version est disponible.

Ivan
